"""empty message

Revision ID: 03636d105a33
Revises: b4cf5be1e545
Create Date: 2023-06-07 11:45:34.176268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03636d105a33'
down_revision = 'b4cf5be1e545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
