"""empty message

Revision ID: 05e95920624e
Revises: bcd7b182b71c
Create Date: 2023-06-02 17:55:20.728118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e95920624e'
down_revision = 'bcd7b182b71c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
