"""empty message

Revision ID: 6647b6f09791
Revises: 03636d105a33
Create Date: 2023-06-07 11:51:32.098805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6647b6f09791'
down_revision = '03636d105a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
