"""empty message

Revision ID: 847450642712
Revises: 3357ae62644e
Create Date: 2023-06-01 11:18:19.526200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847450642712'
down_revision = '3357ae62644e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_type', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_type', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
