"""empty message

Revision ID: b4cf5be1e545
Revises: 05e95920624e
Create Date: 2023-06-05 16:13:49.648953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cf5be1e545'
down_revision = '05e95920624e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
