"""empty message

Revision ID: bcd7b182b71c
Revises: 847450642712
Create Date: 2023-06-02 16:41:12.011305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd7b182b71c'
down_revision = '847450642712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('category_title', 'product_type', ['category_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_title', 'product_type', type_='unique')
    # ### end Alembic commands ###
