"""empty message

Revision ID: f6f8527e43df
Revises: 9b831e7b30b5
Create Date: 2023-06-07 14:56:28.952514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f8527e43df'
down_revision = '9b831e7b30b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS currencyenum")
    op.execute("CREATE TYPE currencyenum AS ENUM ('USD', 'UZS')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE product ALTER COLUMN currency TYPE currencyenum USING currency::currencyenum')
    op.alter_column('product', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UZS', 'USD', name='currencyenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:  
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'currency',
               existing_type=sa.Enum('UZS', 'USD', name='currencyenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS currencyenum")
